// Mocks generated by Mockito 5.4.4 from annotations
// in era_connect/test/pages/main_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:era_connect/api/storage/account_storage.dart' as _i3;
import 'package:era_connect/api/storage/storage_api.dart' as _i4;
import 'package:era_connect/api/storage/ui_layout.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUILayoutStorage_0 extends _i1.SmartFake
    implements _i2.UILayoutStorage {
  _FakeUILayoutStorage_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAccountStorage_1 extends _i1.SmartFake
    implements _i3.AccountStorage {
  _FakeAccountStorage_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StorageApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageApi extends _i1.Mock implements _i4.StorageApi {
  MockStorageApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UILayoutStorage get uiLayout => (super.noSuchMethod(
        Invocation.getter(#uiLayout),
        returnValue: _FakeUILayoutStorage_0(
          this,
          Invocation.getter(#uiLayout),
        ),
      ) as _i2.UILayoutStorage);

  @override
  _i3.AccountStorage get accountStorage => (super.noSuchMethod(
        Invocation.getter(#accountStorage),
        returnValue: _FakeAccountStorage_1(
          this,
          Invocation.getter(#accountStorage),
        ),
      ) as _i3.AccountStorage);
}

/// A class which mocks [UILayoutStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockUILayoutStorage extends _i1.Mock implements _i2.UILayoutStorage {
  MockUILayoutStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get completedSetup => (super.noSuchMethod(
        Invocation.getter(#completedSetup),
        returnValue: false,
      ) as bool);

  @override
  set completedSetup(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #completedSetup,
          value,
        ),
        returnValueForMissingStub: null,
      );
}
