// Mocks generated by Mockito 5.4.2 from annotations
// in era_connect/test/pages/main_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:era_connect/api/config/ui_layout.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UILayoutConfig].
///
/// See the documentation for Mockito's code generation for more information.
class MockUILayoutConfig extends _i1.Mock implements _i2.UILayoutConfig {
  MockUILayoutConfig() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get completedSetup => (super.noSuchMethod(
        Invocation.getter(#completedSetup),
        returnValue: false,
      ) as bool);
  @override
  set completedSetup(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #completedSetup,
          value,
        ),
        returnValueForMissingStub: null,
      );
}
