// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.25.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'ui_layout.freezed.dart';

enum UILayoutKey {
  completedSetup,
}

@freezed
sealed class UILayoutValue with _$UILayoutValue {
  const factory UILayoutValue.completedSetup(
    bool field0,
  ) = UILayoutValue_CompletedSetup;
}
