// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.2.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments
)]

// Section: imports

use crate::api::*;
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::transform_result_dco;
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!();

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire_DownloadProgress_get_p_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    that: impl CstDecode<flutter_rust_bridge::RustOpaque<std::sync::RwLock<crate::api::DownloadProgress>>>
        + core::panic::UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "DownloadProgress_get_p",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_that = that.cst_decode();
            move |context| {
                transform_result_dco((move || {
                    let api_that = api_that.rust_auto_opaque_decode_ref()?;
                    Result::<_, anyhow::Error>::Ok(crate::api::DownloadProgress::get_p(&api_that))
                })())
            }
        },
    )
}
fn wire_create_collection_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    display_name: impl CstDecode<String> + core::panic::UnwindSafe,
    version_metadata: impl CstDecode<crate::api::vanilla::version::VersionMetadata>
        + core::panic::UnwindSafe,
    mod_loader: impl CstDecode<Option<crate::api::collection::ModLoader>> + core::panic::UnwindSafe,
    advanced_options: impl CstDecode<Option<crate::api::collection::AdvancedOptions>>
        + core::panic::UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_collection",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_display_name = display_name.cst_decode();
            let api_version_metadata = version_metadata.cst_decode();
            let api_mod_loader = mod_loader.cst_decode();
            let api_advanced_options = advanced_options.cst_decode();
            move |context| async move {
                transform_result_dco(
                    (move || async move {
                        crate::api::create_collection(
                            api_display_name,
                            api_version_metadata,
                            api_mod_loader,
                            api_advanced_options,
                        )
                        .await
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire_get_account_storage_impl(
    key: impl CstDecode<crate::api::storage::account_storage::AccountStorageKey>
        + core::panic::UnwindSafe,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_account_storage",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let api_key = key.cst_decode();
            transform_result_dco((move || {
                Result::<_, ()>::Ok(crate::api::get_account_storage(api_key))
            })())
        },
    )
}
fn wire_get_skin_file_path_impl(
    skin: impl CstDecode<crate::api::authentication::account::MinecraftSkin> + core::panic::UnwindSafe,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_skin_file_path",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let api_skin = skin.cst_decode();
            transform_result_dco((move || {
                Result::<_, ()>::Ok(crate::api::get_skin_file_path(api_skin))
            })())
        },
    )
}
fn wire_get_ui_layout_storage_impl(
    key: impl CstDecode<crate::api::storage::ui_layout::UILayoutKey> + core::panic::UnwindSafe,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_ui_layout_storage",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let api_key = key.cst_decode();
            transform_result_dco((move || {
                Result::<_, ()>::Ok(crate::api::get_ui_layout_storage(api_key))
            })())
        },
    )
}
fn wire_get_v_impl(port_: flutter_rust_bridge::for_generated::MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "get_v", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || {  move |context|  {
                    transform_result_dco((move ||  {
                         Result::<_,()>::Ok(crate::api::get_v())
                    })())
                } })
}
fn wire_minecraft_login_flow_impl(port_: flutter_rust_bridge::for_generated::MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "minecraft_login_flow", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Stream }, move || {  move |context|  {
                    transform_result_dco((move ||  {
                         crate::api::minecraft_login_flow(StreamSink::new(context.rust2dart_context().stream_sink::<_,crate::api::authentication::msa_flow::LoginFlowEvent>()))
                    })())
                } })
}
fn wire_remove_minecraft_account_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    uuid: impl CstDecode<uuid::Uuid> + core::panic::UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "remove_minecraft_account",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_uuid = uuid.cst_decode();
            move |context| {
                transform_result_dco((move || crate::api::remove_minecraft_account(api_uuid))())
            }
        },
    )
}
fn wire_set_ui_layout_storage_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    value: impl CstDecode<crate::api::storage::ui_layout::UILayoutValue> + core::panic::UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "set_ui_layout_storage",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_value = value.cst_decode();
            move |context| {
                transform_result_dco((move || crate::api::set_ui_layout_storage(api_value))())
            }
        },
    )
}
fn wire_setup_logger_impl(port_: flutter_rust_bridge::for_generated::MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "setup_logger",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || move |context| transform_result_dco((move || crate::api::setup_logger())()),
    )
}

// Section: dart2rust

impl CstDecode<chrono::DateTime<chrono::Utc>> for i64 {
    fn cst_decode(self) -> chrono::DateTime<chrono::Utc> {
        let flutter_rust_bridge::for_generated::Timestamp { s, ns } =
            flutter_rust_bridge::for_generated::decode_timestamp(self);
        chrono::DateTime::<chrono::Utc>::from_naive_utc_and_offset(
            chrono::NaiveDateTime::from_timestamp_opt(s, ns)
                .expect("invalid or out-of-range datetime"),
            chrono::Utc,
        )
    }
}
impl CstDecode<crate::api::storage::account_storage::AccountStorageKey> for i32 {
    fn cst_decode(self) -> crate::api::storage::account_storage::AccountStorageKey {
        match self {
            0 => crate::api::storage::account_storage::AccountStorageKey::Accounts,
            1 => crate::api::storage::account_storage::AccountStorageKey::MainAccount,
            _ => unreachable!("Invalid variant for AccountStorageKey: {}", self),
        }
    }
}
impl CstDecode<bool> for bool {
    fn cst_decode(self) -> bool {
        self
    }
}
impl CstDecode<f64> for f64 {
    fn cst_decode(self) -> f64 {
        self
    }
}
impl CstDecode<i32> for i32 {
    fn cst_decode(self) -> i32 {
        self
    }
}
impl CstDecode<i64> for i64 {
    fn cst_decode(self) -> i64 {
        self
    }
}
impl CstDecode<crate::api::authentication::msa_flow::LoginFlowStage> for i32 {
    fn cst_decode(self) -> crate::api::authentication::msa_flow::LoginFlowStage {
        match self {
            0 => crate::api::authentication::msa_flow::LoginFlowStage::FetchingDeviceCode,
            1 => crate::api::authentication::msa_flow::LoginFlowStage::WaitingForUser,
            2 => crate::api::authentication::msa_flow::LoginFlowStage::AuthenticatingXboxLive,
            3 => crate::api::authentication::msa_flow::LoginFlowStage::FetchingXstsToken,
            4 => crate::api::authentication::msa_flow::LoginFlowStage::FetchingMinecraftToken,
            5 => crate::api::authentication::msa_flow::LoginFlowStage::GettingProfile,
            _ => unreachable!("Invalid variant for LoginFlowStage: {}", self),
        }
    }
}
impl CstDecode<crate::api::authentication::account::MinecraftSkinVariant> for i32 {
    fn cst_decode(self) -> crate::api::authentication::account::MinecraftSkinVariant {
        match self {
            0 => crate::api::authentication::account::MinecraftSkinVariant::Classic,
            1 => crate::api::authentication::account::MinecraftSkinVariant::Slim,
            _ => unreachable!("Invalid variant for MinecraftSkinVariant: {}", self),
        }
    }
}
impl CstDecode<crate::api::collection::ModLoaderType> for i32 {
    fn cst_decode(self) -> crate::api::collection::ModLoaderType {
        match self {
            0 => crate::api::collection::ModLoaderType::Forge,
            1 => crate::api::collection::ModLoaderType::NeoForge,
            2 => crate::api::collection::ModLoaderType::Fabric,
            3 => crate::api::collection::ModLoaderType::Quilt,
            _ => unreachable!("Invalid variant for ModLoaderType: {}", self),
        }
    }
}
impl CstDecode<u32> for u32 {
    fn cst_decode(self) -> u32 {
        self
    }
}
impl CstDecode<u8> for u8 {
    fn cst_decode(self) -> u8 {
        self
    }
}
impl CstDecode<crate::api::storage::ui_layout::UILayoutKey> for i32 {
    fn cst_decode(self) -> crate::api::storage::ui_layout::UILayoutKey {
        match self {
            0 => crate::api::storage::ui_layout::UILayoutKey::CompletedSetup,
            _ => unreachable!("Invalid variant for UILayoutKey: {}", self),
        }
    }
}
impl CstDecode<usize> for usize {
    fn cst_decode(self) -> usize {
        self
    }
}
impl CstDecode<crate::api::vanilla::version::VersionType> for i32 {
    fn cst_decode(self) -> crate::api::vanilla::version::VersionType {
        match self {
            0 => crate::api::vanilla::version::VersionType::Release,
            1 => crate::api::vanilla::version::VersionType::Snapshot,
            2 => crate::api::vanilla::version::VersionType::OldBeta,
            3 => crate::api::vanilla::version::VersionType::OldAlpha,
            _ => unreachable!("Invalid variant for VersionType: {}", self),
        }
    }
}
impl CstDecode<crate::api::authentication::msa_flow::XstsTokenErrorType> for i32 {
    fn cst_decode(self) -> crate::api::authentication::msa_flow::XstsTokenErrorType {
        match self {
            0 => crate::api::authentication::msa_flow::XstsTokenErrorType::DoesNotHaveXboxAccount,
            1 => crate::api::authentication::msa_flow::XstsTokenErrorType::CountryNotAvailable,
            2 => {
                crate::api::authentication::msa_flow::XstsTokenErrorType::NeedsAdultVerificationKR1
            }
            3 => {
                crate::api::authentication::msa_flow::XstsTokenErrorType::NeedsAdultVerificationKR2
            }
            4 => crate::api::authentication::msa_flow::XstsTokenErrorType::ChildAccount,
            _ => unreachable!("Invalid variant for XstsTokenErrorType: {}", self),
        }
    }
}
impl SseDecode for anyhow::Error {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        unimplemented!("not yet supported in serialized mode, feel free to create an issue");
    }
}

impl SseDecode for chrono::DateTime<chrono::Utc> {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        unimplemented!("not yet supported in serialized mode, feel free to create an issue");
    }
}

impl SseDecode
    for flutter_rust_bridge::RustOpaque<std::sync::RwLock<crate::api::DownloadProgress>>
{
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <usize>::sse_decode(deserializer);
        return unsafe { flutter_rust_bridge::for_generated::sse_decode_rust_opaque(inner) };
    }
}

impl SseDecode for String {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for uuid::Uuid {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        unimplemented!("not yet supported in serialized mode, feel free to create an issue");
    }
}

impl SseDecode for crate::api::storage::account_storage::AccountStorageKey {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::storage::account_storage::AccountStorageKey::Accounts,
            1 => crate::api::storage::account_storage::AccountStorageKey::MainAccount,
            _ => unreachable!("Invalid variant for AccountStorageKey: {}", inner),
        };
    }
}

impl SseDecode for crate::api::storage::account_storage::AccountStorageValue {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_field0 =
                    <Vec<crate::api::authentication::account::MinecraftAccount>>::sse_decode(
                        deserializer,
                    );
                return crate::api::storage::account_storage::AccountStorageValue::Accounts(
                    var_field0,
                );
            }
            1 => {
                let mut var_field0 = <Option<uuid::Uuid>>::sse_decode(deserializer);
                return crate::api::storage::account_storage::AccountStorageValue::MainAccount(
                    var_field0,
                );
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::authentication::account::AccountToken {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_token = <String>::sse_decode(deserializer);
        let mut var_expiresAt = <i64>::sse_decode(deserializer);
        return crate::api::authentication::account::AccountToken {
            token: var_token,
            expires_at: var_expiresAt,
        };
    }
}

impl SseDecode for crate::api::collection::AdvancedOptions {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_jvmMaxMemory = <Option<usize>>::sse_decode(deserializer);
        return crate::api::collection::AdvancedOptions {
            jvm_max_memory: var_jvmMaxMemory,
        };
    }
}

impl SseDecode for bool {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::collection::CollectionId {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_field0 = <String>::sse_decode(deserializer);
        return crate::api::collection::CollectionId(var_field0);
    }
}

impl SseDecode for f64 {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i32 {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i64 {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<crate::api::authentication::account::MinecraftAccount> {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(
                <crate::api::authentication::account::MinecraftAccount>::sse_decode(deserializer),
            );
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::authentication::account::MinecraftCape> {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(
                <crate::api::authentication::account::MinecraftCape>::sse_decode(deserializer),
            );
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::authentication::account::MinecraftSkin> {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(
                <crate::api::authentication::account::MinecraftSkin>::sse_decode(deserializer),
            );
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode
    for Vec<(
        crate::api::collection::CollectionId,
        crate::api::download::Progress,
    )>
{
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<(
                crate::api::collection::CollectionId,
                crate::api::download::Progress,
            )>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::authentication::msa_flow::LoginFlowDeviceCode {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_verificationUri = <String>::sse_decode(deserializer);
        let mut var_userCode = <String>::sse_decode(deserializer);
        return crate::api::authentication::msa_flow::LoginFlowDeviceCode {
            verification_uri: var_verificationUri,
            user_code: var_userCode,
        };
    }
}

impl SseDecode for crate::api::authentication::msa_flow::LoginFlowErrors {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_field0 =
                    <crate::api::authentication::msa_flow::XstsTokenErrorType>::sse_decode(
                        deserializer,
                    );
                return crate::api::authentication::msa_flow::LoginFlowErrors::XstsError(
                    var_field0,
                );
            }
            1 => {
                return crate::api::authentication::msa_flow::LoginFlowErrors::GameNotOwned;
            }
            2 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::api::authentication::msa_flow::LoginFlowErrors::UnknownError(
                    var_field0,
                );
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::authentication::msa_flow::LoginFlowEvent {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_field0 =
                    <crate::api::authentication::msa_flow::LoginFlowStage>::sse_decode(
                        deserializer,
                    );
                return crate::api::authentication::msa_flow::LoginFlowEvent::Stage(var_field0);
            }
            1 => {
                let mut var_field0 =
                    <crate::api::authentication::msa_flow::LoginFlowDeviceCode>::sse_decode(
                        deserializer,
                    );
                return crate::api::authentication::msa_flow::LoginFlowEvent::DeviceCode(
                    var_field0,
                );
            }
            2 => {
                let mut var_field0 =
                    <crate::api::authentication::msa_flow::LoginFlowErrors>::sse_decode(
                        deserializer,
                    );
                return crate::api::authentication::msa_flow::LoginFlowEvent::Error(var_field0);
            }
            3 => {
                let mut var_field0 =
                    <crate::api::authentication::account::MinecraftAccount>::sse_decode(
                        deserializer,
                    );
                return crate::api::authentication::msa_flow::LoginFlowEvent::Success(var_field0);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::authentication::msa_flow::LoginFlowStage {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::authentication::msa_flow::LoginFlowStage::FetchingDeviceCode,
            1 => crate::api::authentication::msa_flow::LoginFlowStage::WaitingForUser,
            2 => crate::api::authentication::msa_flow::LoginFlowStage::AuthenticatingXboxLive,
            3 => crate::api::authentication::msa_flow::LoginFlowStage::FetchingXstsToken,
            4 => crate::api::authentication::msa_flow::LoginFlowStage::FetchingMinecraftToken,
            5 => crate::api::authentication::msa_flow::LoginFlowStage::GettingProfile,
            _ => unreachable!("Invalid variant for LoginFlowStage: {}", inner),
        };
    }
}

impl SseDecode for crate::api::authentication::account::MinecraftAccount {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_username = <String>::sse_decode(deserializer);
        let mut var_uuid = <uuid::Uuid>::sse_decode(deserializer);
        let mut var_accessToken =
            <crate::api::authentication::account::AccountToken>::sse_decode(deserializer);
        let mut var_refreshToken =
            <crate::api::authentication::account::AccountToken>::sse_decode(deserializer);
        let mut var_skins =
            <Vec<crate::api::authentication::account::MinecraftSkin>>::sse_decode(deserializer);
        let mut var_capes =
            <Vec<crate::api::authentication::account::MinecraftCape>>::sse_decode(deserializer);
        return crate::api::authentication::account::MinecraftAccount {
            username: var_username,
            uuid: var_uuid,
            access_token: var_accessToken,
            refresh_token: var_refreshToken,
            skins: var_skins,
            capes: var_capes,
        };
    }
}

impl SseDecode for crate::api::authentication::account::MinecraftCape {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <uuid::Uuid>::sse_decode(deserializer);
        let mut var_state = <String>::sse_decode(deserializer);
        let mut var_url = <String>::sse_decode(deserializer);
        let mut var_alias = <String>::sse_decode(deserializer);
        return crate::api::authentication::account::MinecraftCape {
            id: var_id,
            state: var_state,
            url: var_url,
            alias: var_alias,
        };
    }
}

impl SseDecode for crate::api::authentication::account::MinecraftSkin {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <uuid::Uuid>::sse_decode(deserializer);
        let mut var_state = <String>::sse_decode(deserializer);
        let mut var_url = <String>::sse_decode(deserializer);
        let mut var_variant =
            <crate::api::authentication::account::MinecraftSkinVariant>::sse_decode(deserializer);
        return crate::api::authentication::account::MinecraftSkin {
            id: var_id,
            state: var_state,
            url: var_url,
            variant: var_variant,
        };
    }
}

impl SseDecode for crate::api::authentication::account::MinecraftSkinVariant {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::authentication::account::MinecraftSkinVariant::Classic,
            1 => crate::api::authentication::account::MinecraftSkinVariant::Slim,
            _ => unreachable!("Invalid variant for MinecraftSkinVariant: {}", inner),
        };
    }
}

impl SseDecode for crate::api::collection::ModLoader {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_modLoaderType =
            <crate::api::collection::ModLoaderType>::sse_decode(deserializer);
        let mut var_version = <String>::sse_decode(deserializer);
        return crate::api::collection::ModLoader {
            mod_loader_type: var_modLoaderType,
            version: var_version,
        };
    }
}

impl SseDecode for crate::api::collection::ModLoaderType {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::collection::ModLoaderType::Forge,
            1 => crate::api::collection::ModLoaderType::NeoForge,
            2 => crate::api::collection::ModLoaderType::Fabric,
            3 => crate::api::collection::ModLoaderType::Quilt,
            _ => unreachable!("Invalid variant for ModLoaderType: {}", inner),
        };
    }
}

impl SseDecode for Option<uuid::Uuid> {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<uuid::Uuid>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::collection::AdvancedOptions> {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::collection::AdvancedOptions>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::collection::ModLoader> {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::collection::ModLoader>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<usize> {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<usize>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::download::Progress {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_speed = <f64>::sse_decode(deserializer);
        let mut var_percentages = <f64>::sse_decode(deserializer);
        let mut var_currentSize = <f64>::sse_decode(deserializer);
        let mut var_totalSize = <f64>::sse_decode(deserializer);
        return crate::api::download::Progress {
            speed: var_speed,
            percentages: var_percentages,
            current_size: var_currentSize,
            total_size: var_totalSize,
        };
    }
}

impl SseDecode
    for (
        crate::api::collection::CollectionId,
        crate::api::download::Progress,
    )
{
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_field0 = <crate::api::collection::CollectionId>::sse_decode(deserializer);
        let mut var_field1 = <crate::api::download::Progress>::sse_decode(deserializer);
        return (var_field0, var_field1);
    }
}

impl SseDecode for u32 {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for crate::api::storage::ui_layout::UILayoutKey {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::storage::ui_layout::UILayoutKey::CompletedSetup,
            _ => unreachable!("Invalid variant for UILayoutKey: {}", inner),
        };
    }
}

impl SseDecode for crate::api::storage::ui_layout::UILayoutValue {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_field0 = <bool>::sse_decode(deserializer);
                return crate::api::storage::ui_layout::UILayoutValue::CompletedSetup(var_field0);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for () {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for usize {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap() as _
    }
}

impl SseDecode for crate::api::vanilla::version::VersionMetadata {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_versionType =
            <crate::api::vanilla::version::VersionType>::sse_decode(deserializer);
        let mut var_url = <String>::sse_decode(deserializer);
        let mut var_uploadedTime = <chrono::DateTime<chrono::Utc>>::sse_decode(deserializer);
        let mut var_releaseTime = <chrono::DateTime<chrono::Utc>>::sse_decode(deserializer);
        let mut var_sha1 = <String>::sse_decode(deserializer);
        let mut var_complianceLevel = <u32>::sse_decode(deserializer);
        return crate::api::vanilla::version::VersionMetadata {
            id: var_id,
            version_type: var_versionType,
            url: var_url,
            uploaded_time: var_uploadedTime,
            release_time: var_releaseTime,
            sha1: var_sha1,
            compliance_level: var_complianceLevel,
        };
    }
}

impl SseDecode for crate::api::vanilla::version::VersionType {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::vanilla::version::VersionType::Release,
            1 => crate::api::vanilla::version::VersionType::Snapshot,
            2 => crate::api::vanilla::version::VersionType::OldBeta,
            3 => crate::api::vanilla::version::VersionType::OldAlpha,
            _ => unreachable!("Invalid variant for VersionType: {}", inner),
        };
    }
}

impl SseDecode for crate::api::authentication::msa_flow::XstsTokenErrorType {
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::authentication::msa_flow::XstsTokenErrorType::DoesNotHaveXboxAccount,
            1 => crate::api::authentication::msa_flow::XstsTokenErrorType::CountryNotAvailable,
            2 => {
                crate::api::authentication::msa_flow::XstsTokenErrorType::NeedsAdultVerificationKR1
            }
            3 => {
                crate::api::authentication::msa_flow::XstsTokenErrorType::NeedsAdultVerificationKR2
            }
            4 => crate::api::authentication::msa_flow::XstsTokenErrorType::ChildAccount,
            _ => unreachable!("Invalid variant for XstsTokenErrorType: {}", inner),
        };
    }
}

// Section: rust2dart

impl flutter_rust_bridge::IntoDart for crate::api::storage::account_storage::AccountStorageKey {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Accounts => 0,
            Self::MainAccount => 1,
        }
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::storage::account_storage::AccountStorageKey
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::storage::account_storage::AccountStorageKey>
    for crate::api::storage::account_storage::AccountStorageKey
{
    fn into_into_dart(self) -> crate::api::storage::account_storage::AccountStorageKey {
        self
    }
}
impl flutter_rust_bridge::IntoDart for crate::api::storage::account_storage::AccountStorageValue {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::storage::account_storage::AccountStorageValue::Accounts(field0) => {
                vec![0.into_dart(), field0.into_into_dart().into_dart()]
            }
            crate::api::storage::account_storage::AccountStorageValue::MainAccount(field0) => {
                vec![1.into_dart(), field0.into_into_dart().into_dart()]
            }
        }
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::storage::account_storage::AccountStorageValue
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::storage::account_storage::AccountStorageValue>
    for crate::api::storage::account_storage::AccountStorageValue
{
    fn into_into_dart(self) -> crate::api::storage::account_storage::AccountStorageValue {
        self
    }
}
impl flutter_rust_bridge::IntoDart for crate::api::authentication::account::AccountToken {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        vec![
            self.token.into_into_dart().into_dart(),
            self.expires_at.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::authentication::account::AccountToken
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::authentication::account::AccountToken>
    for crate::api::authentication::account::AccountToken
{
    fn into_into_dart(self) -> crate::api::authentication::account::AccountToken {
        self
    }
}
impl flutter_rust_bridge::IntoDart for crate::api::collection::AdvancedOptions {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        vec![self.jvm_max_memory.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::collection::AdvancedOptions
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::collection::AdvancedOptions>
    for crate::api::collection::AdvancedOptions
{
    fn into_into_dart(self) -> crate::api::collection::AdvancedOptions {
        self
    }
}
impl flutter_rust_bridge::IntoDart for crate::api::collection::CollectionId {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        vec![self.0.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::collection::CollectionId
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::collection::CollectionId>
    for crate::api::collection::CollectionId
{
    fn into_into_dart(self) -> crate::api::collection::CollectionId {
        self
    }
}
impl flutter_rust_bridge::IntoDart for crate::api::authentication::msa_flow::LoginFlowDeviceCode {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        vec![
            self.verification_uri.into_into_dart().into_dart(),
            self.user_code.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::authentication::msa_flow::LoginFlowDeviceCode
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::authentication::msa_flow::LoginFlowDeviceCode>
    for crate::api::authentication::msa_flow::LoginFlowDeviceCode
{
    fn into_into_dart(self) -> crate::api::authentication::msa_flow::LoginFlowDeviceCode {
        self
    }
}
impl flutter_rust_bridge::IntoDart for crate::api::authentication::msa_flow::LoginFlowErrors {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::authentication::msa_flow::LoginFlowErrors::XstsError(field0) => {
                vec![0.into_dart(), field0.into_into_dart().into_dart()]
            }
            crate::api::authentication::msa_flow::LoginFlowErrors::GameNotOwned => {
                vec![1.into_dart()]
            }
            crate::api::authentication::msa_flow::LoginFlowErrors::UnknownError(field0) => {
                vec![2.into_dart(), field0.into_into_dart().into_dart()]
            }
        }
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::authentication::msa_flow::LoginFlowErrors
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::authentication::msa_flow::LoginFlowErrors>
    for crate::api::authentication::msa_flow::LoginFlowErrors
{
    fn into_into_dart(self) -> crate::api::authentication::msa_flow::LoginFlowErrors {
        self
    }
}
impl flutter_rust_bridge::IntoDart for crate::api::authentication::msa_flow::LoginFlowEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::authentication::msa_flow::LoginFlowEvent::Stage(field0) => {
                vec![0.into_dart(), field0.into_into_dart().into_dart()]
            }
            crate::api::authentication::msa_flow::LoginFlowEvent::DeviceCode(field0) => {
                vec![1.into_dart(), field0.into_into_dart().into_dart()]
            }
            crate::api::authentication::msa_flow::LoginFlowEvent::Error(field0) => {
                vec![2.into_dart(), field0.into_into_dart().into_dart()]
            }
            crate::api::authentication::msa_flow::LoginFlowEvent::Success(field0) => {
                vec![3.into_dart(), field0.into_into_dart().into_dart()]
            }
        }
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::authentication::msa_flow::LoginFlowEvent
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::authentication::msa_flow::LoginFlowEvent>
    for crate::api::authentication::msa_flow::LoginFlowEvent
{
    fn into_into_dart(self) -> crate::api::authentication::msa_flow::LoginFlowEvent {
        self
    }
}
impl flutter_rust_bridge::IntoDart for crate::api::authentication::msa_flow::LoginFlowStage {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::FetchingDeviceCode => 0,
            Self::WaitingForUser => 1,
            Self::AuthenticatingXboxLive => 2,
            Self::FetchingXstsToken => 3,
            Self::FetchingMinecraftToken => 4,
            Self::GettingProfile => 5,
        }
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::authentication::msa_flow::LoginFlowStage
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::authentication::msa_flow::LoginFlowStage>
    for crate::api::authentication::msa_flow::LoginFlowStage
{
    fn into_into_dart(self) -> crate::api::authentication::msa_flow::LoginFlowStage {
        self
    }
}
impl flutter_rust_bridge::IntoDart for crate::api::authentication::account::MinecraftAccount {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        vec![
            self.username.into_into_dart().into_dart(),
            self.uuid.into_into_dart().into_dart(),
            self.access_token.into_into_dart().into_dart(),
            self.refresh_token.into_into_dart().into_dart(),
            self.skins.into_into_dart().into_dart(),
            self.capes.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::authentication::account::MinecraftAccount
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::authentication::account::MinecraftAccount>
    for crate::api::authentication::account::MinecraftAccount
{
    fn into_into_dart(self) -> crate::api::authentication::account::MinecraftAccount {
        self
    }
}
impl flutter_rust_bridge::IntoDart for crate::api::authentication::account::MinecraftCape {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        vec![
            self.id.into_into_dart().into_dart(),
            self.state.into_into_dart().into_dart(),
            self.url.into_into_dart().into_dart(),
            self.alias.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::authentication::account::MinecraftCape
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::authentication::account::MinecraftCape>
    for crate::api::authentication::account::MinecraftCape
{
    fn into_into_dart(self) -> crate::api::authentication::account::MinecraftCape {
        self
    }
}
impl flutter_rust_bridge::IntoDart for crate::api::authentication::account::MinecraftSkin {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        vec![
            self.id.into_into_dart().into_dart(),
            self.state.into_into_dart().into_dart(),
            self.url.into_into_dart().into_dart(),
            self.variant.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::authentication::account::MinecraftSkin
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::authentication::account::MinecraftSkin>
    for crate::api::authentication::account::MinecraftSkin
{
    fn into_into_dart(self) -> crate::api::authentication::account::MinecraftSkin {
        self
    }
}
impl flutter_rust_bridge::IntoDart for crate::api::authentication::account::MinecraftSkinVariant {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Classic => 0,
            Self::Slim => 1,
        }
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::authentication::account::MinecraftSkinVariant
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::authentication::account::MinecraftSkinVariant>
    for crate::api::authentication::account::MinecraftSkinVariant
{
    fn into_into_dart(self) -> crate::api::authentication::account::MinecraftSkinVariant {
        self
    }
}
impl flutter_rust_bridge::IntoDart for crate::api::collection::ModLoader {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        vec![
            self.mod_loader_type.into_into_dart().into_dart(),
            self.version.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::collection::ModLoader
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::collection::ModLoader>
    for crate::api::collection::ModLoader
{
    fn into_into_dart(self) -> crate::api::collection::ModLoader {
        self
    }
}
impl flutter_rust_bridge::IntoDart for crate::api::collection::ModLoaderType {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Forge => 0,
            Self::NeoForge => 1,
            Self::Fabric => 2,
            Self::Quilt => 3,
        }
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::collection::ModLoaderType
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::collection::ModLoaderType>
    for crate::api::collection::ModLoaderType
{
    fn into_into_dart(self) -> crate::api::collection::ModLoaderType {
        self
    }
}
impl flutter_rust_bridge::IntoDart for crate::api::download::Progress {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        vec![
            self.speed.into_into_dart().into_dart(),
            self.percentages.into_into_dart().into_dart(),
            self.current_size.into_into_dart().into_dart(),
            self.total_size.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::download::Progress
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::download::Progress>
    for crate::api::download::Progress
{
    fn into_into_dart(self) -> crate::api::download::Progress {
        self
    }
}
impl flutter_rust_bridge::IntoDart for crate::api::storage::ui_layout::UILayoutKey {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::CompletedSetup => 0,
        }
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::storage::ui_layout::UILayoutKey
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::storage::ui_layout::UILayoutKey>
    for crate::api::storage::ui_layout::UILayoutKey
{
    fn into_into_dart(self) -> crate::api::storage::ui_layout::UILayoutKey {
        self
    }
}
impl flutter_rust_bridge::IntoDart for crate::api::storage::ui_layout::UILayoutValue {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::storage::ui_layout::UILayoutValue::CompletedSetup(field0) => {
                vec![0.into_dart(), field0.into_into_dart().into_dart()]
            }
        }
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::storage::ui_layout::UILayoutValue
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::storage::ui_layout::UILayoutValue>
    for crate::api::storage::ui_layout::UILayoutValue
{
    fn into_into_dart(self) -> crate::api::storage::ui_layout::UILayoutValue {
        self
    }
}
impl flutter_rust_bridge::IntoDart for crate::api::vanilla::version::VersionMetadata {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        vec![
            self.id.into_into_dart().into_dart(),
            self.version_type.into_into_dart().into_dart(),
            self.url.into_into_dart().into_dart(),
            self.uploaded_time.into_into_dart().into_dart(),
            self.release_time.into_into_dart().into_dart(),
            self.sha1.into_into_dart().into_dart(),
            self.compliance_level.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::vanilla::version::VersionMetadata
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::vanilla::version::VersionMetadata>
    for crate::api::vanilla::version::VersionMetadata
{
    fn into_into_dart(self) -> crate::api::vanilla::version::VersionMetadata {
        self
    }
}
impl flutter_rust_bridge::IntoDart for crate::api::vanilla::version::VersionType {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Release => 0,
            Self::Snapshot => 1,
            Self::OldBeta => 2,
            Self::OldAlpha => 3,
        }
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::vanilla::version::VersionType
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::vanilla::version::VersionType>
    for crate::api::vanilla::version::VersionType
{
    fn into_into_dart(self) -> crate::api::vanilla::version::VersionType {
        self
    }
}
impl flutter_rust_bridge::IntoDart for crate::api::authentication::msa_flow::XstsTokenErrorType {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::DoesNotHaveXboxAccount => 0,
            Self::CountryNotAvailable => 1,
            Self::NeedsAdultVerificationKR1 => 2,
            Self::NeedsAdultVerificationKR2 => 3,
            Self::ChildAccount => 4,
        }
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::authentication::msa_flow::XstsTokenErrorType
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::authentication::msa_flow::XstsTokenErrorType>
    for crate::api::authentication::msa_flow::XstsTokenErrorType
{
    fn into_into_dart(self) -> crate::api::authentication::msa_flow::XstsTokenErrorType {
        self
    }
}

impl SseEncode for anyhow::Error {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode for chrono::DateTime<chrono::Utc> {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("not yet supported in serialized mode, feel free to create an issue");
    }
}

impl SseEncode
    for flutter_rust_bridge::RustOpaque<std::sync::RwLock<crate::api::DownloadProgress>>
{
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        let (ptr, size) = self.sse_encode_raw();
        <usize>::sse_encode(ptr, serializer);
        <i32>::sse_encode(size, serializer);
    }
}

impl SseEncode for String {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for uuid::Uuid {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("not yet supported in serialized mode, feel free to create an issue");
    }
}

impl SseEncode for crate::api::storage::account_storage::AccountStorageKey {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self as _, serializer);
    }
}

impl SseEncode for crate::api::storage::account_storage::AccountStorageValue {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::storage::account_storage::AccountStorageValue::Accounts(field0) => {
                <i32>::sse_encode(0, serializer);
                <Vec<crate::api::authentication::account::MinecraftAccount>>::sse_encode(
                    field0, serializer,
                );
            }
            crate::api::storage::account_storage::AccountStorageValue::MainAccount(field0) => {
                <i32>::sse_encode(1, serializer);
                <Option<uuid::Uuid>>::sse_encode(field0, serializer);
            }
        }
    }
}

impl SseEncode for crate::api::authentication::account::AccountToken {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.token, serializer);
        <i64>::sse_encode(self.expires_at, serializer);
    }
}

impl SseEncode for crate::api::collection::AdvancedOptions {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<usize>>::sse_encode(self.jvm_max_memory, serializer);
    }
}

impl SseEncode for bool {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::collection::CollectionId {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.0, serializer);
    }
}

impl SseEncode for f64 {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i32 {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i64 {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<crate::api::authentication::account::MinecraftAccount> {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::authentication::account::MinecraftAccount>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::authentication::account::MinecraftCape> {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::authentication::account::MinecraftCape>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::authentication::account::MinecraftSkin> {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::authentication::account::MinecraftSkin>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode
    for Vec<(
        crate::api::collection::CollectionId,
        crate::api::download::Progress,
    )>
{
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <(
                crate::api::collection::CollectionId,
                crate::api::download::Progress,
            )>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::authentication::msa_flow::LoginFlowDeviceCode {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.verification_uri, serializer);
        <String>::sse_encode(self.user_code, serializer);
    }
}

impl SseEncode for crate::api::authentication::msa_flow::LoginFlowErrors {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::authentication::msa_flow::LoginFlowErrors::XstsError(field0) => {
                <i32>::sse_encode(0, serializer);
                <crate::api::authentication::msa_flow::XstsTokenErrorType>::sse_encode(
                    field0, serializer,
                );
            }
            crate::api::authentication::msa_flow::LoginFlowErrors::GameNotOwned => {
                <i32>::sse_encode(1, serializer);
            }
            crate::api::authentication::msa_flow::LoginFlowErrors::UnknownError(field0) => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(field0, serializer);
            }
        }
    }
}

impl SseEncode for crate::api::authentication::msa_flow::LoginFlowEvent {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::authentication::msa_flow::LoginFlowEvent::Stage(field0) => {
                <i32>::sse_encode(0, serializer);
                <crate::api::authentication::msa_flow::LoginFlowStage>::sse_encode(
                    field0, serializer,
                );
            }
            crate::api::authentication::msa_flow::LoginFlowEvent::DeviceCode(field0) => {
                <i32>::sse_encode(1, serializer);
                <crate::api::authentication::msa_flow::LoginFlowDeviceCode>::sse_encode(
                    field0, serializer,
                );
            }
            crate::api::authentication::msa_flow::LoginFlowEvent::Error(field0) => {
                <i32>::sse_encode(2, serializer);
                <crate::api::authentication::msa_flow::LoginFlowErrors>::sse_encode(
                    field0, serializer,
                );
            }
            crate::api::authentication::msa_flow::LoginFlowEvent::Success(field0) => {
                <i32>::sse_encode(3, serializer);
                <crate::api::authentication::account::MinecraftAccount>::sse_encode(
                    field0, serializer,
                );
            }
        }
    }
}

impl SseEncode for crate::api::authentication::msa_flow::LoginFlowStage {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self as _, serializer);
    }
}

impl SseEncode for crate::api::authentication::account::MinecraftAccount {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.username, serializer);
        <uuid::Uuid>::sse_encode(self.uuid, serializer);
        <crate::api::authentication::account::AccountToken>::sse_encode(
            self.access_token,
            serializer,
        );
        <crate::api::authentication::account::AccountToken>::sse_encode(
            self.refresh_token,
            serializer,
        );
        <Vec<crate::api::authentication::account::MinecraftSkin>>::sse_encode(
            self.skins, serializer,
        );
        <Vec<crate::api::authentication::account::MinecraftCape>>::sse_encode(
            self.capes, serializer,
        );
    }
}

impl SseEncode for crate::api::authentication::account::MinecraftCape {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <uuid::Uuid>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.state, serializer);
        <String>::sse_encode(self.url, serializer);
        <String>::sse_encode(self.alias, serializer);
    }
}

impl SseEncode for crate::api::authentication::account::MinecraftSkin {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <uuid::Uuid>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.state, serializer);
        <String>::sse_encode(self.url, serializer);
        <crate::api::authentication::account::MinecraftSkinVariant>::sse_encode(
            self.variant,
            serializer,
        );
    }
}

impl SseEncode for crate::api::authentication::account::MinecraftSkinVariant {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self as _, serializer);
    }
}

impl SseEncode for crate::api::collection::ModLoader {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::collection::ModLoaderType>::sse_encode(self.mod_loader_type, serializer);
        <String>::sse_encode(self.version, serializer);
    }
}

impl SseEncode for crate::api::collection::ModLoaderType {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self as _, serializer);
    }
}

impl SseEncode for Option<uuid::Uuid> {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <uuid::Uuid>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::collection::AdvancedOptions> {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::collection::AdvancedOptions>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::collection::ModLoader> {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::collection::ModLoader>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<usize> {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <usize>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::download::Progress {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f64>::sse_encode(self.speed, serializer);
        <f64>::sse_encode(self.percentages, serializer);
        <f64>::sse_encode(self.current_size, serializer);
        <f64>::sse_encode(self.total_size, serializer);
    }
}

impl SseEncode
    for (
        crate::api::collection::CollectionId,
        crate::api::download::Progress,
    )
{
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::collection::CollectionId>::sse_encode(self.0, serializer);
        <crate::api::download::Progress>::sse_encode(self.1, serializer);
    }
}

impl SseEncode for u32 {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for crate::api::storage::ui_layout::UILayoutKey {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self as _, serializer);
    }
}

impl SseEncode for crate::api::storage::ui_layout::UILayoutValue {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::storage::ui_layout::UILayoutValue::CompletedSetup(field0) => {
                <i32>::sse_encode(0, serializer);
                <bool>::sse_encode(field0, serializer);
            }
        }
    }
}

impl SseEncode for () {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for usize {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer
            .cursor
            .write_u64::<NativeEndian>(self as _)
            .unwrap();
    }
}

impl SseEncode for crate::api::vanilla::version::VersionMetadata {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <crate::api::vanilla::version::VersionType>::sse_encode(self.version_type, serializer);
        <String>::sse_encode(self.url, serializer);
        <chrono::DateTime<chrono::Utc>>::sse_encode(self.uploaded_time, serializer);
        <chrono::DateTime<chrono::Utc>>::sse_encode(self.release_time, serializer);
        <String>::sse_encode(self.sha1, serializer);
        <u32>::sse_encode(self.compliance_level, serializer);
    }
}

impl SseEncode for crate::api::vanilla::version::VersionType {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self as _, serializer);
    }
}

impl SseEncode for crate::api::authentication::msa_flow::XstsTokenErrorType {
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self as _, serializer);
    }
}

#[cfg(not(target_family = "wasm"))]
#[path = "frb_generated.io.rs"]
mod io;
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
#[path = "frb_generated.web.rs"]
mod web;
#[cfg(target_family = "wasm")]
pub use web::*;
