// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AdvancedOptions {
  final int? jvmMaxMemory;

  const AdvancedOptions({
    this.jvmMaxMemory,
  });

  @override
  int get hashCode => jvmMaxMemory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AdvancedOptions &&
          runtimeType == other.runtimeType &&
          jvmMaxMemory == other.jvmMaxMemory;
}

class CollectionId {
  final String field0;

  const CollectionId({
    required this.field0,
  });

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CollectionId &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}

class ModLoader {
  final ModLoaderType modLoaderType;
  final String version;

  const ModLoader({
    required this.modLoaderType,
    required this.version,
  });

  @override
  int get hashCode => modLoaderType.hashCode ^ version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModLoader &&
          runtimeType == other.runtimeType &&
          modLoaderType == other.modLoaderType &&
          version == other.version;
}

enum ModLoaderType {
  forge,
  neoForge,
  fabric,
  quilt,
}
