name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Install Flutter SDK
          uses: subosito/flutter-action@v2
          with:
            flutter-version: "3.10.5"
            channel: "stable"
            cache: true
        - name: Install Rust Language
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            override: true
            components: rustfmt, clippy
        - name: Test And Generate Coverage
          run: |
            cd app
            flutter pub get
            flutter test --coverage

            cd packages
            for d in */ ; do
              cd $d
              flutter pub get
              flutter test --coverage --coverage-path ../../coverage/lcov.info --merge-coverage
              cd ..
            done
        - name: Upload Coverage
          uses: codecov/codecov-action@v3
          with:
            files: coverage/lcov.info
            fail_ci_if_error: true